import { reactive } from "vue";
export const vinylInfo = reactive([
  {
    name: "UTOPIA",
    artist: "Travis Scott",
    img: "https://m.media-amazon.com/images/I/41ZO3L5IIXL._UF1000,1000_QL80_.jpg",
    price: "$27.99",
    rare: false,
    inCart: false,
  },
  {
    name: "Dark Side of the Moon",
    artist: "Pink Floyd",
    img: "https://m.media-amazon.com/images/I/31+szRBlJyL._SY300_.jpg",
    price: "$28.97",
    rare: false,
    inCart: false,
  },
  {
    name: "Thriller",
    artist: "Michael Jackson",
    img: "https://m.media-amazon.com/images/I/51vnfQPXskL._SX300_SY300_QL70_FMwebp_.jpg",
    price: "$19.97",
    rare: false,
    inCart: false,
  },
  {
    name: "Abbey Road",
    artist: "The Beatles",
    img: "https://usastore.thebeatles.com/cdn/shop/products/abbey-road-1lp_b42fc887-7b22-4568-92cd-4298f40715f8.png?v=1661531925",
    price: "$26.50",
    rare: false,
    inCart: false,
  },
  {
    name: "Back in Black",
    artist: "AC:DC",
    img: "https://m.media-amazon.com/images/I/71s6glEqRyL._SX425_.jpg",
    price: "$25.98",
    rare: false,
    inCart: false,
  },
  {
    name: "The Wall",
    artist: "Pink Floyd",
    img: "https://m.media-amazon.com/images/I/41Etqd29z5L._SX425_.jpg",
    price: "$55.99",
    rare: true,
    inCart: false,
  },
  {
    name: "Rumours",
    artist: "Fleetwood Mac",
    img: "https://m.media-amazon.com/images/I/71HWqbh0BLL._SX425_.jpg",
    price: "$24.89",
    rare: false,
    inCart: false,
  },
  {
    name: "Led Zeppelin IV",
    artist: "Led Zeppelin",
    img: "https://m.media-amazon.com/images/I/619OnDt1yvL._SX300_SY300_QL70_FMwebp_.jpg",
    price: "$22.89",
    rare: false,
    inCart: false,
  },
  {
    name: "Pet Sounds",
    artist: "The Beach Boys",
    img: "https://m.media-amazon.com/images/I/41hjX6hfRpL._SX300_SY300_QL70_FMwebp_.jpg",
    price: "$29.96",
    rare: false,
    inCart: false,
  },
  {
    name: "A Night at the Opera",
    artist: "Queen",
    img: "https://m.media-amazon.com/images/I/41mfODvDFtL._SX300_SY300_QL70_FMwebp_.jpg",
    price: "$28.96",
    rare: false,
    inCart: false,
  },
  {
    name: "Graceland",
    artist: "Paul Simon",
    img: "https://m.media-amazon.com/images/I/71Posnz98jL._SX425_.jpg",
    price: "$24.99",
    rare: false,
    inCart: false,
  },
]);
